### ISSUE TITLE
経験値トラップ

### ISSUE THREAD

**Issue by kyoh86** [thinca/minecraft-vim-jp-tasks#10]
- [ ] 作る
- [ ] marker置く

**Comment by kyoh86** [comment]
エンダーマン式が素直。超効率を求めるならネザー岩盤上のゾンビピグリントラップ。
ただ、ネザー岩盤上なのでいつ仕様的に殺されてもおかしくない。

**Comment by thinca** [comment]
エンダーマン式だとエンド行った後ですかね?

**Comment by kyoh86** [comment]
ですねー。めっちゃ神経使うヤツ #19

**Comment by thinca** [comment]
アイアンゴーレムトラップの真下にゾンビピグリントラップを作りました。立ってるだけで経験値が入ります。

**Comment by thinca** [comment]
ブレイズトラップもエンダーマントラップも作った。
