### ISSUE TITLE
青森までの道を整備する

### ISSUE THREAD

**Issue by kyoh86** [thinca/minecraft-vim-jp-tasks#14]
ネザーの青森（歪んだ森）までの整備。
- [x] 位置を特定する
- [x] markerを置く
- [x] 安全な道を整備する

**Comment by ujihisa** [comment]
![2023-04-07_09 32 07](https://user-images.githubusercontent.com/11504/230644453-3bc7024f-f11b-4345-ad56-c1d2a1c4f263.png)

**Comment by ujihisa** [comment]
安全な道は整備した。あとは金に余裕があれば鉄道でポータルからつなぎたいところ
