### ISSUE TITLE
砂漠を見つける

### ISSUE THREAD

**Issue by kyoh86** [thinca/minecraft-vim-jp-tasks#15]
見つける。サボテンとかほしい。

**Comment by thinca** [comment]
サボテンは行商人からゲットしました。

**Comment by kyoh86** [comment]
桜アップデート近いし、徒にロードされた範囲広げない意味でも急がない。
1.20まで待ち（ワールド読み込み範囲を広げたくない）

**Comment by kyoh86** [comment]
見つかった。 -3000, 2600
