### ISSUE TITLE
新拠点: 自動かまど

### ISSUE THREAD

**Issue by kyoh86** [thinca/minecraft-vim-jp-tasks#32]
新拠点側に。鉱石倉庫なんかとアクセスが良いことが大事。

**Comment by kyoh86** [comment]
## 自動かまどの高速化

自動かまどを大量に作る目的は、 **精錬速度の向上** である。
つまり、多くのかまどで分担して一度に精錬を行うことで、1アイテム/10秒の速度を(かまど数)/10秒で消化しようとしている。

## 高速化するための燃料の効率

実用上、大量のアイテムを一度に精錬することがあったとしても、1かまどあたりのアイテム数は6個程度である（＝全体で60秒程度で精錬が終わる）ことが望ましい。
つまり、「1つの燃料でどれだけ大量のアイテムを焼けるか」はあまり重要ではない。
（6個程度焼ければ十分である）

燃料ごとの燃焼時間は以下の通り。
https://minecraft.fandom.com/ja/wiki/%E3%81%8B%E3%81%BE%E3%81%A9/table

むしろ、燃料を生産する効率が高い、補給の途絶えにくい燃料の選択が重要である。

## 燃料を無限化できるか

### 無限カーペット

カーペット無限増殖バグは、エンドポータルを利用した無限砂/砂利装置同様にかなり古くから存在し、無限かまどといえばこれ、というくらいには定番化している。
効率は極めて高い。

### バグを利用しない燃料

無限に生産可能、かつ自動生産が可能な燃料アイテム群を列挙。

| 燃料 | 燃焼時間 (※1) | 無限化 | 自動生産 |
| --- | --- | --- | --- |
| 溶岩バケツ | 1000秒 |  可能 | 半自動化可能 (※2) |
| ブレイズロッド | 120秒 | 可能 | 可能 |
| 木炭 | 80秒 | 可能 | 可能（※3） |
| 原木 | 15秒 | 可能 | 可能（※3） |
| 羊毛 | 5秒 | 可能 | 可能 |
| 竹 | 2.5秒 | 可能 | 可能 (※4) |

- ※1 燃焼時間10秒で1アイテムの精錬が行える。
- ※2 ユーザーがインベントリを調整し、右クリックし続ける必要がある
    - https://www.youtube.com/watch?v=KMW7llnbx_I
- ※3 ただし、原木の回収機構はTNT（バグ無しでは無限化できない）を使ったもの、ウィザーを使ったもの（超大規模・高難度化する）しかない
- ※4 自動骨粉製造装置→自動竹製造装置の接続

### バグを利用しない燃料の生産効率

- 溶岩バケツ
- ブレイズロッド
- 羊毛
- 竹

について、現実的に必要な生産効率と、それを実現するために必要な条件を考えるべき。
おそらく用意するべき装置の規模がボトルネックになってくる。

**Comment by kyoh86** [comment]
### 羊毛の生産効率

1マスに3頭、波及元の草ブロックを周囲に7マス置いた状態で、5.5時間放置した結果、80個。
約1個/250秒
1かまど当たり1個/5秒で消費されるので、消費スピードと同等に生産できる体制を作るには
50マスに150頭の羊が要る。
そんな常時精錬するわけではないので、1/10くらいに抑えて5マス15頭かな。

羊の頭数が強く影響しているかは怪しいが、草ブロックになる→羊が食べる　の間隔は多少短くなる…はず。
あとは土ブロック→草ブロック化の速度をどれだけ上げられるかが効率の鍵を握ると思う。

**Comment by kyoh86** [comment]
s/7マス/6マス

**Comment by kyoh86** [comment]
伝播元草ブロック15個、実際の閉じ込めは3ブロック、羊を30頭で27スタック/9時間。
つまり3スタック/1時間=3.2個/分なので、約1個/20秒。十分では？
これをあとは何かまど置くか、という話で十分そう。

**Comment by thinca** [comment]
ブレイズロッドによるかまどが作られました。
