### ISSUE TITLE
シュルカートラップ

### ISSUE THREAD

**Issue by kyoh86** [thinca/minecraft-vim-jp-tasks#37]
一応参考動画:
https://youtu.be/dMBDbZXSORs

考慮漏れが多いので修正を加えてSchema化したモノ:
https://drive.google.com/file/d/1alNpsTpWC8yn3Aj3bddt3FQ_QbbP0-Qq/view?usp=sharing

エンド要塞の近く、ただし装置から20ブロック内にはものが置けない（シュルカーがワープしてしまう）ので、マージンを取って30ブロックくらい離した位置で作る。

**Comment by kyoh86** [comment]
- 透明化のポーションがいる
    - https://game8.jp/minecraft/222698
    - 発行したクモの目がいる
        - 茶色いキノコがいる
    - 暗視のポーションがいる
        - https://game8.jp/minecraft/222699
        - 金ニンジン
- ソウルサンド集めがいる

**Comment by kyoh86** [comment]
## 外装付き

Schematics: https://drive.google.com/file/d/1BxJRlkxY46OX1KcXMuV-wAKpMhn3xgxC/view?usp=drive_link
素材リスト: https://docs.google.com/spreadsheets/d/1bL_-wTHXzLzrqTQrKN-3gYvHI0AbT2-eGkrmrtZRFOY/edit#gid=1096496135
実際の稼働している風景（動画）: https://youtu.be/H4T68ljMv_M

**Comment by kyoh86** [comment]
- Placement origin:
    - x: -1034
    - y: 58
    - z: -297
- Rotation: CW_90
- Mirror: NONE

**Comment by thinca** [comment]
トロッコはディスペンサーで一定時間置きに排出 & 古いのは回収方式に改修した。
残りは外装部分。
